### ISSUE TITLE
Different Idle Slot Appearance 

### ISSUE THREAD

**Issue by charlie-chester** [pacemaker82/PredBat-Table-Card#28]
Sorry to open this up again but why is this image from my Laptop not showing the little chg when the one on my iphone is?

<img width="783" alt="Overview_–_Home_Assistant" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/7441121f-d987-43b1-a9b8-af4a6c43ce47">

![Screenshot 2024-05-13 at 22 49 04](https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/96287470-10d8-4fb8-8661-907faa4f1a2d)

_Originally posted by @charlie-chester in https://github.com/pacemaker82/PredBat-Table-Card/issues/27#issuecomment-2108695470_

**Comment by charlie-chester** [comment]
Also today I see one slot has colour but the other doesn't. 

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/bdfac8cd-2950-4ebe-bf8a-0de548f72261)

**Comment by pacemaker82** [comment]
The lack of colour means that predbat is not doing anything, its charging or discharging as normal (aka "idle" mode). The "bug" here is that is says "Chg" which suggests it is predbat doing some charging - but its not, it should just be an arrow. 

> Also today I see one slot has colour but the other doesn't.
> 
> ![image](https://private-user-images.githubusercontent.com/133705626/331190015-bdfac8cd-2950-4ebe-bf8a-0de548f72261.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzMyODAsIm5iZiI6MTcxNjk3Mjk4MCwicGF0aCI6Ii8xMzM3MDU2MjYvMzMxMTkwMDE1LWJkZmFjOGNkLTI5NTAtNGViZS1iZjhhLTBkZTU0OGY3MjI2MS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMDg1NjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWVjODJmZTE4MzQ2ZmQ3YTgzOGRlMjY4NWMxYTA0Zjc5OWQ0OTBiMDBjY2ZhNTMxYTJhOTZlYzVmNmM0MDhmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PKJyMVllc5p-lSjNtE3rwsdWGTNkTrPXgs5wqYh64ys)

**Comment by pacemaker82** [comment]
I see what you mean though, there is grey and white "Chg" cells... I will look into that one

**Comment by pacemaker82** [comment]
This should be resolved in https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.3.7 which I just pushed out.

> Also today I see one slot has colour but the other doesn't.
> 
> ![image](https://private-user-images.githubusercontent.com/133705626/331190015-bdfac8cd-2950-4ebe-bf8a-0de548f72261.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzU2ODksIm5iZiI6MTcxNjk3NTM4OSwicGF0aCI6Ii8xMzM3MDU2MjYvMzMxMTkwMDE1LWJkZmFjOGNkLTI5NTAtNGViZS1iZjhhLTBkZTU0OGY3MjI2MS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMDkzNjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWNkZTMyMDJjYzU1MDRlN2ZmM2QxNGRiYTRhMDBiNTY3ZjgyMjk5NzlhMjdjOWJmMDg3YzhhZGZlN2FkYjBkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JQZe42oc30lXuLJhyILRHXatenyjeqsLyGPQPoEwLcg)

**Comment by charlie-chester** [comment]
I've just installed this and cleared the cache as advised. I now don't see any colour just white but I still see the Chg when the screen is narrow!

I've got this set up as per your notes for using on my iPhone with less columns when it's in portrait and more if in landscape. this works really well but when I view in portrait I see the Chg but in landscape it shows without.  

![IMG_3159](https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/0d15e668-ab78-4982-aa7a-2ded2a0d5e09)

![IMG_3160](https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/bd8d500b-be26-410d-b7f6-d0660638c353)

**Comment by pacemaker82** [comment]
yes the wording hasnt been removed yet on mobile. Yet to find the culprit to that.

**Comment by charlie-chester** [comment]
OK cool. Great work there mate. I'm on Intel Flux at the moment so this is an every day thing so can test for you if needed just give me a shout.

**Comment by pacemaker82** [comment]
@charlie-chester please give https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.3.8 a go.

**Comment by pacemaker82** [comment]
ah sorry about that, can you try https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.3.9

**Comment by charlie-chester** [comment]
That's better thanks. 

Nice work there again. Really impressed with this little gem you've made. 

I've just started to lean to code. I can only dream about creating something like this.

**Comment by charlie-chester** [comment]
I hate to tell you this but the Chg is back!

And today's slots are a lot wider than tomorrow's. 

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/94260367-a588-4fc4-af1c-fa3407e04fc0)

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/516cf2a7-f2a9-4c1f-b0f7-e78f768806ea)

**Comment by pacemaker82** [comment]
Are you clearing your cache on the iphone app? This looks like you have an old javascript being run...

Goto Home Assistant Settings, there is a menu for "Companion App" (you need to be on the device to see this)

"Debugging" > "Reset Frontend Cache" - then go back to your dashboard and refresh.

**Comment by charlie-chester** [comment]
type: vertical-stack
cards:
  - type: conditional
    conditions:
      - condition: screen
        media_query: '(min-width: 0px) and (max-width: 767px)'
    card:
      type: custom:predbat-table-card
      entity: predbat.plan_html
      columns:
        - time-column
        - state-column
        - limit-column
        - soc-column
        - cost-column
        - total-column
      odd_row_colour: '#181f2a'
      even_row_colour: '#2a3240'
      fill_empty_cells: true
      stack_pills: false
      old_skool: true
  - type: conditional
    conditions:
      - condition: screen
        media_query: '(min-width: 768px)'
    card:
      type: custom:predbat-table-card
      entity: predbat.plan_html
      columns:
        - time-column
        - import-column
        - state-column
        - limit-column
        - pv-column
        - load-column
        - soc-column
        - cost-column
        - total-column
      table_width: 100
      fill_empty_cells: true
      stack_pills: false
      old_skool: true

**Comment by charlie-chester** [comment]
https://gist.github.com/charlie-chester/c987e8045c291a3f79f147d724541633

**Comment by charlie-chester** [comment]
I can also see this happening in Chrome on my Mac if I drag the window size very small.

**Comment by pacemaker82** [comment]
are there any other cards on that dashboard page? Its really strange as its working fine here with your card config.

**Comment by charlie-chester** [comment]
No it's set 1 panel. If you want to share screen I'll show you in on the Mac.

**Comment by pacemaker82** [comment]
Could you send me a screenshot of the original predbat plan showing the affected rows? Want to make sure there's nothing odd there in the source

**Comment by charlie-chester** [comment]
![IMG_3165](https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/3ae6f2e3-9f27-421c-9f77-7a74e15a6843)

**Comment by pacemaker82** [comment]
whats enabled there to create those last two columns?

**Comment by charlie-chester** [comment]
It's the kerning on the text I think just pushing it very slightly to make Thu go on a different line. Or maybe the word Discharge in a split slot pushing stuff over 

<img width="781" alt="Different_Idle_Slot_Appearance_·_Issue__28_·_pacemaker82_PredBat-Table-Card" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/c709700e-3c45-49c2-93ec-767a2ced2fba">

Yesterday when I thought it was OK it wasn't a split slot.

**Comment by charlie-chester** [comment]
> whats enabled there to create those last two columns?

It's the Carbon. Don't use it in your card.

**Comment by charlie-chester** [comment]
I'm on a iPhone 13 Pro. Maybe my screen is a few pixels smaller than your so mine won't display on same line. 

If I take a column out it's OK apart from still showing the Chg.

![IMG_3166](https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/ea56b716-11b1-425e-9d21-eb4d3bc79589)

**Comment by pacemaker82** [comment]
i can only think that your HA has downloaded an old js file and you're running it out of date (or its got mixed up somehow) because the code to show Chg with up arrow just isnt there anymore in latest. Maybe try through HACS to redownload the JS? 

Meaning this display is impossible with the latest code:
<img width="776" alt="Screenshot 2024-05-30 at 15 28 11" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/78989741-f09b-4bdc-9488-16a24653a693">

I installed the carbon stuff to see if that was affecting it but its not.

I'm going to have to rewrite this part of code, just need a couple of days to figure it out

**Comment by charlie-chester** [comment]
I've just removed Table Card. Restarted Home Assistant cleared the Cache and then put it back on. 

It's still the same so don't know why. 

Tomorrows 4pm slot has just come into view and thats normal sized lines so its the Thu thats messing with today as it's very slightly bigger. (never had trouble others Thursdays though)

Tomorrow is interesting as the Chg that you said the code isn't there is showing again!

![IMG_3167](https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/4dcfc0e4-7f2e-43e1-8d87-4533dac9e999)

![IMG_3168](https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/fbf89b7a-fbee-44b3-af14-6603997ccf72)

**Comment by charlie-chester** [comment]
This is tomorrow on the original plan. It's showing as idle but going up. Does that make any difference? Does you plan interpret that as charge?

<img width="760" alt="Overview_–_Home_Assistant" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/7866872a-b34e-4ef0-b93f-0d23e65f7953">

**Comment by charlie-chester** [comment]
Just had another look and it seems to be back to normal today with normal thin lines. 

I wonder if it's eventually cleared that rogue file from the cache!

I'll keep an eye out the next couple of days and report back. 

Thanks again for a great bit of kit.

**Comment by charlie-chester** [comment]
Morning mate. I hope you don't mind me bombarding you with this I'm just trying to help you out as I know you can't repeat it. 

I appreciate all the hard work you put in. 

Anyway. Today's Chg is back and tomorrow had wide lines again. 

I really don't know what to do. I've removed the add on and restarted a million times. 

Just for info. 

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/9c57920d-35ac-432c-ae81-c88b6f17c044)

**Comment by charlie-chester** [comment]
Cheers mate. Just for info thats sorted my height error but not the Chg. 

Nice work mate very much appreciated.

**Comment by pacemaker82** [comment]
@charlie-chester I think this should now be [fixed and available in 1.5.5.5](https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.5.5) - not 100% sure but please have a go and let me know.

**Comment by charlie-chester** [comment]
On first view mate it all looks brilliant. I will monitor over the next few days to see as some different day names made a differnce to the column width.

Just like to add how brilliant this card is and how well youve made it and kept on top of slight errors and people like me!!!

Cheers.

**Comment by pacemaker82** [comment]
Thanks @charlie-chester - will close this ticket for now, please re-open if same issue occurs.
